// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function GetUsers(arg1:string):Promise<db.Zt_user>;

export function Greet(arg1:string):Promise<string>;
